import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    )!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
  _AppLocalizationsDelegate();

  static const supportedLocales = [
    Locale('en'),
    Locale('fr'),
  ];

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // General
      'app_name': 'Home237',
      'settings': 'App Settings',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'logout': 'Log out',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      
      // Auth
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'login': 'Login',
      'register': 'Register',
      'continue_with_google': 'Continue with Google',
      'email': 'Email',
      'password': 'Password',
      'email_hint': 'Enter your email',
      'password_hint': 'Enter your password',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': 'Don\'t have an account?',
      'already_have_account': 'Already have an account?',
      'create_account': 'Create Account',
      'welcome_back': 'Welcome Back',
      'remember_me': 'Remember Me',
      'sign_in_failed': 'Sign in failed',
      
      // Home / Dashboard
      'home': 'Home',
      'explore': 'Explore',
      'near_you': 'Near You',
      'featured': 'Featured',
      'hero_title': 'Find your perfect home',
      'hero_in_city_beyond': 'in {city} & beyond',
      'hero_across_cameroon': 'across Cameroon 🇨🇲',
      'search_hint': 'Search city, area, or property...',
      'all': 'All',
      'listings_available': 'listings available',
      'no_listings': 'No listings yet',
      'clear_filter': 'Clear filter',
      'see_all': 'See all',
      'browse_all': 'Browse all',
      'top_pick': 'Top Pick',
      'per_month': '/ mo',
      'beds': 'beds',
      'verified': 'Verified',
      
      // Verification
      'verify_title': 'Verify Your Email',
      'verify_sent_to': 'We\'ve sent a verification email to:',
      'verify_body': 'Please check your inbox, including the Spam or Primary folders. Click the verification link in the email, then return here and click the button below.',
      'ive_verified': 'I\'ve Verified My Email',
      'resend_link': 'Resend Verification Email',
      'resend_wait': 'Resend Link in',
      'verification_strict_error': 'Our system shows you haven\'t clicked the link in your email yet. Please check your Gmail (including Spam) and click it to continue.',
      'verification_email_sent': 'Verification email sent! Please check your inbox.',
      'error_sending_email': 'Error sending email',
      'error_checking_verification': 'Error checking verification',
      'error_completing_signup': 'Error completing signup',
      'verify_instructions_title': 'Follow these steps:',
      'verify_step_1': 'Open your Gmail app or mail inbox',
      'verify_step_2': 'Find the e-mail from Home237',
      'verify_step_3': 'Click the verification link inside',
      'waiting_for_verification': 'Waiting for verification...',
      'click_link_first': 'Please click the link in your email first',
      'click_link_then_tap': 'Open your Gmail, click the verification link, then come back and tap \'I\'ve Verified\' below.',
      
      // Admin
      'admin_overview': 'APPEARANCE',
      'users': 'Users',
      'properties': 'Properties',
      'cities': 'Cities',
      'verifications': 'Verifications',
      'reports': 'Reports',
      'support': 'Support',
      'account_settings': 'ACCOUNT SETTINGS',
      'user_role': 'User Role',
      'change_password': 'Change Password',
      'full_name': 'Full Name',
      'full_name_hint': 'Enter your full name',
      'confirm_password': 'Confirm Password',
      'confirm_password_hint': 'Confirm your password',
      'passwords_dont_match': 'Passwords do not match',
      'sign_in_to_continue': 'Sign in to continue',
      'sign_in_up_button': 'Sign In / Sign Up',
      'continue_browsing': 'Continue browsing',
      'press_back_to_close': 'Press back again to close the app',
      'no_results_found': 'No results found',
      'near_you_at': 'Near You',
      'near_you_dash': 'Near You — {city}',
      'no_listings_near_you': 'No {filter}listings near you yet',
      'get_verified': 'Get Verified',
      'upload_docs_desc': 'Upload documents for verification',
      'verification_pending': 'Verification Pending',
      'wait_admin_approval': 'Wait for admin approval',
      'verification_rejected': 'Verification Rejected',
      'reupload_rejected_docs': 'Your documents were rejected. Please re-upload.',
      're_verify': 'Re-verify',
      'verify': 'Verify',
      'welcome_for_first_time': 'Welcome for the first time,',
      'upgrade_to_premium': 'Upgrade to Premium?',
      'upgrade_premium_desc': 'Did you know Premium Landlords get their properties listed at the very top of search results and enjoy unlimited listings?\n\nWould you like to upgrade before posting?',
      'maybe_later': 'Maybe Later',
      'yes_upgrade': 'Yes, Upgrade',
      'let_get_started': 'Let\'s Get Started',
      'welcome_home237': 'Welcome to Home237!',
      'landlord_welcome_body': 'The best platform to manage your properties in Cameroon 🇨🇲. We\'re thrilled to have you here!',
      'overview': 'Overview',
      'total_properties': 'Total Properties',
      'active': 'Active',
      'pending_tours': 'Pending Tours',
      'total_views': 'Total Views',
      'quick_actions': 'Quick Actions',
      'add_property': 'Add Property',
      'upgrade': 'Upgrade',
      'explore_properties': 'Explore Properties',
      'all_regions': 'All Regions',
      'search_explore_hint': 'Search by city, area, or type…',
      'featured_caps': 'FEATURED',
      'no_properties_found': 'No properties found',
      'no_results_for': 'No results for "{query}"',
      'try_different_keyword': 'Try a different keyword',
      'try_different_area': 'Try a different area or region',
      'logout_confirm': 'Are you sure you want to log out?',
      'privacy_security': 'Privacy & Security',
      'notifications': 'NOTIFICATIONS',
      'push_notifications': 'Push Notifications',
      'email_marketing': 'Email Marketing',
      'legal': 'LEGAL',
      'tos': 'Terms of Service',
      'privacy_policy': 'Privacy Policy',
      'delete_account': 'Delete Account',
      'delete_account_desc': 'Permanently delete your account and data',
      'version': 'Version',
      'change_password_title': 'Change Password',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_new_password': 'Confirm New Password',
      'password_updated': 'Password changed successfully!',
      'phone_number': 'Phone Number',
      'phone_number_required': 'Please enter your phone number',
      'photo_permission_required': 'Please enable photo permission in settings',
      'photo_permission_denied': 'Photo permission denied',

      // Bottom Nav
      'nav_home': 'HOME',
      'nav_explore': 'EXPLORE',
      'nav_saved': 'SAVED',
      'nav_messages': 'MESSAGES',
      'nav_profile': 'PROFILE',
      'nav_dashboard': 'DASHBOARD',
      'nav_properties': 'PROPERTIES',
      'nav_tours': 'TOURS',

      // Onboarding
      'skip': 'Skip',
      'welcome_home237_intro': 'The #1 platform to find and list\nhomes in Cameroon 🇨🇲',
      'browse': 'Browse',
      'save': 'Save',
      'chat': 'Chat',
      'tour': 'Tour',
      'everything_you_need': 'Everything You Need',
      'hunter_effortless_body': 'Discover the features that make\nhome hunting effortless.',
      'verified_listings_title': 'Verified Listings',
      'verified_listings_body': 'Every property is reviewed and approved by our admin team.',
      'find_near_you_title': 'Find Near You',
      'find_near_you_body': 'Browse properties closest to your current location in Cameroon.',
      'chat_landlords_title': 'Chat with Landlords',
      'chat_landlords_body': 'Message landlords directly and schedule property tours.',
      'save_favorites_title': 'Save Favorites',
      'save_favorites_body': 'Bookmark properties and revisit them anytime.',
      'where_looking': 'Where Are You Looking?',
      'personalize_feed_body': 'We\'ll personalize your home feed\nbased on your location in Cameroon.',
      'detect_my_location': 'Detect My Location',
      'detecting_your_location': 'Detecting your location...',
      'city_detected': '📍 {city} detected!',
      'change_city': 'Change city',
      'location_not_available_pick': 'Location not available. Please pick a city below.',
      'or_choose_city': 'Or choose a city:',
      'select_city_continue': 'Select a city to continue',
      'explore_in_city': 'Explore Properties in {city} 🏠',
      'next_location_setup': 'Next — Location Setup',
      
      // Validation
      'err_email_empty': 'Please enter your email',
      'err_email_invalid': 'Please enter a valid email',
      'err_password_empty': 'Please enter your password',
      'err_name_empty': 'Please enter your full name',
      'err_confirm_password_empty': 'Please confirm your password',
      'password_too_short': 'Password must be at least 6 characters',
      
      // Profile
      'edit_profile': 'Edit Profile',
      'personal_info': 'PERSONAL INFORMATION',
      'business_info': 'BUSINESS INFORMATION',
      'rental_pref': 'RENTAL PREFERENCES',
      'pref_location': 'Preferred Location',
      'prop_type': 'Property Type',
      'min_budget': 'Min Budget (FCFA)',
      'max_budget': 'Max Budget (FCFA)',
      'tap_change_photo': 'Tap to change photo',
      'save_changes': 'Save',
      'business_email': 'Business Email',
      'company_name': 'Company/Business Name',
      'address': 'Property Address',
      'verified_landlord': 'VERIFIED LANDLORD',
      'delete_permanently': 'Delete Permanently',
      'enter_password_confirm': 'Enter your password to confirm:',
      'delete_warning_tenant': 'This action is permanent and will delete all your data, including saved properties, messages, and your profile.',
      'delete_warning_landlord': 'This action is permanent and will delete all your data, including properties and favorites.',
      'studio': 'Studio Apartment',
      '1bed': '1 Bedroom',
      '2bed': '2 Bedrooms',
      '3bed': '3+ Bedrooms',
      'house': 'House',
      'condo': 'Condo',
      'profile_updated': 'Profile updated successfully!',
      'photo_updated': 'Profile picture updated!',
      
      // Roles
      'tenant': 'Tenant',
      'landlord': 'Landlord',
      'tenant_desc': 'Looking for a place to rent',
      'landlord_desc': 'Have properties to rent out',
      'select_role': 'Select your role',
      
      // Terms and Privacy (summarized keys)
      'tos_title': 'Terms of Service',
      'tos_updated': 'Last updated: 4 March 2026',
      'tos_s1_t': '1. Acceptance of Terms',
      'tos_s1_b': 'By accessing and using the Home237 application, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.',
      'tos_s2_t': '2. User Responsibilities',
      'tos_s2_b': 'You must be at least 18 years of age to use this Application. By using the Application you warrant that you are at least 18 years of age. You agree to use the App for lawful purposes only and in a way that does not infringe the rights of others.',
      'tos_s3_t': '3. Property Listings',
      'tos_s3_b': 'Landlords are responsible for the accuracy of their property listings. Home237 does not verify all claims in listings and is not liable for discrepancies between listed and actual property features.',
      'tos_s4_t': '4. Payments and Subscriptions',
      'tos_s4_b': 'Certain features of the Application require payment. All fees are quoted in FCFA and are non-refundable unless expressly required by applicable law. Premium subscriptions renew automatically until cancelled.',
      'tos_s5_t': '5. Intellectual Property',
      'tos_s5_b': 'The Application and its original content, features, and functionality are owned by Home237 and are protected by applicable intellectual property laws.',
      'tos_s6_t': '6. Limitation of Liability',
      'tos_s6_b': 'Home237 shall not be liable for any indirect, incidental, special, consequential or punitive damages, including loss of profits or data, resulting from your use of the service.',
      'tos_s7_t': '7. Termination',
      'tos_s7_b': 'We may terminate or suspend your account and access to the service immediately, without prior notice, if you breach these Terms.',
      'tos_s8_t': '8. Changes to Terms',
      'tos_s8_b': 'We reserve the right to modify or replace these Terms at any time. By continuing to use the service after any changes become effective, you agree to be bound by the revised terms.',
      'tos_s9_t': '9. Governing Law',
      'tos_s9_b': 'These Terms shall be governed by and construed in accordance with the laws of Cameroon, without regard to its conflict of law provisions.',
      'tos_s10_t': '10. Contact Us',
      'tos_s10_b': 'If you have any questions about these Terms, please contact us at:\nlegal@home237.com',
      'pp_title': 'Privacy Policy',
      'pp_updated': 'Last updated: 4 March 2026',
      'pp_s1_t': '1. Information We Collect',
      'pp_s1_b': 'We collect information you provide directly to us, such as when you create an account, including your name, email address, phone number, profile photo, and property preferences. We also collect information automatically when you use the Application, such as your IP address and device information.',
      'pp_s2_t': '2. How We Use Your Information',
      'pp_s2_b': 'We use the information we collect to:\n• Provide, operate, and maintain our services\n• Process transactions and send related information\n• Send promotional communications (where permitted)\n• Respond to your comments and questions\n• Monitor and analyze usage and trends',
      'pp_s3_t': '3. Sharing of Information',
      'pp_s3_b': 'We may share your information with:\n• Landlords or tenants to facilitate property transactions\n• Third-party service providers who perform services on our behalf\n• Law enforcement when required by law\n\nWe do not sell your personal information to third parties.',
      'pp_s4_t': '4. Data Security',
      'pp_s4_b': 'We take reasonable measures including administrative, technical, and physical safeguards to protect your information from loss, theft, misuse, and unauthorized access. However, no internet transmission is completely secure.',
      'pp_s5_t': '5. Data Retention',
      'pp_s5_b': 'We retain your personal information for as long as your account is active or as needed to provide you services and comply with our legal obligations.',
      'pp_s6_t': '6. Cookies and Tracking',
      'pp_s6_b': 'We may use cookies and similar tracking technologies to track activity on our Application and hold certain information to improve your user experience.',
      'pp_s7_t': '7. Your Rights and Choices',
      'pp_s7_b': 'You may:\n• Access and update your account information at any time\n• Opt out of promotional emails\n• Request deletion of your account by emailing support@home237.com\n• Request a copy of your personal data',
      'pp_s8_t': '8. Children\'s Privacy',
      'pp_s8_b': 'Our service is not directed to children under 18. We do not knowingly collect personal information from children under 18.',
      'pp_s9_t': '9. Changes to This Policy',
      'pp_s9_b': 'We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new policy on this page with an updated date.',
      'pp_s10_t': '10. Contact Us',
      'pp_s10_b': 'If you have any questions about this Privacy Policy, please contact us at:\nprivacy@home237.com\n\nHome237 — Connecting Cameroon\'s tenants and landlords.',
      'tos_footer': '© 2026 Home237. All rights reserved.',
      'pp_footer': '© 2026 Home237. All rights reserved.',
    },
    'fr': {
      // General
      'app_name': 'Home237',
      'settings': 'Paramètres',
      'dark_mode': 'Mode Sombre',
      'language': 'Langue',
      'logout': 'Déconnexion',
      'loading': 'Chargement...',
      'error': 'Erreur',
      'success': 'Succès',
      'cancel': 'Annuler',
      'confirm': 'Confirmer',
      
      // Auth
      'sign_in': 'Se Connecter',
      'sign_up': 'S\'inscrire',
      'login': 'Connexion',
      'register': 'Inscription',
      'continue_with_google': 'Continuer avec Google',
      'email': 'Email',
      'password': 'Mot de passe',
      'email_hint': 'Entrez votre email',
      'password_hint': 'Entrez votre mot de passe',
      'forgot_password': 'Mot de passe oublié ?',
      'dont_have_account': 'Vous n\'avez pas de compte ?',
      'already_have_account': 'Vous avez déjà un compte ?',
      'create_account': 'Créer un compte',
      'welcome_back': 'Bon retour',
      'remember_me': 'Se souvenir de moi',
      'sign_in_failed': 'Échec de la connexion',
      
      // Home / Dashboard
      'home': 'Accueil',
      'explore': 'Explorer',
      'near_you': 'Près de chez vous',
      'featured': 'À la Une',
      'hero_title': 'Trouvez votre maison idéale',
      'hero_in_city_beyond': 'à {city} et au-delà',
      'hero_across_cameroon': 'à travers le Cameroun 🇨🇲',
      'search_hint': 'Rechercher ville, quartier...',
      'all': 'Tout',
      'listings_available': 'annonces disponibles',
      'no_listings': 'Aucune annonce pour le moment',
      'clear_filter': 'Effacer le filtre',
      'see_all': 'Voir tout',
      'browse_all': 'Tout parcourir',
      'top_pick': 'Meilleur choix',
      'per_month': '/ mois',
      'beds': 'chambres',
      'verified': 'Vérifié',
      
      // Verification
      'verify_title': 'Vérifiez votre Email',
      'verify_sent_to': 'Nous avons envoyé un email de vérification à :',
      'verify_body': 'Veuillez consulter votre boîte de réception, y compris les dossiers Spam ou Promotions. Cliquez sur le lien de vérification, puis revenez ici et cliquez sur le bouton ci-dessous.',
      'ive_verified': 'J\'ai vérifié mon email',
      'resend_link': 'Renvoyer l\'email de vérification',
      'resend_wait': 'Renvoyer le lien dans',
      'verification_strict_error': 'Notre système indique que vous n\'avez pas encore cliqué sur le lien dans votre email. Veuillez vérifier votre boîte Gmail (y compris les spams) et cliquer dessus pour continuer.',
      'verification_email_sent': 'Email de vérification envoyé ! Veuillez consulter votre boîte de réception.',
      'error_sending_email': 'Erreur lors de l\'envoi de l\'email',
      'error_checking_verification': 'Erreur lors de la vérification',
      'error_completing_signup': 'Erreur lors de la finalisation de l\'inscription',
      'verify_instructions_title': 'Suivez ces étapes :',
      'verify_step_1': 'Ouvrez votre application Gmail ou votre boîte mail',
      'verify_step_2': 'Trouvez l\'e-mail de Home237',
      'verify_step_3': 'Cliquez sur le lien de vérification à l\'intérieur',
      'waiting_for_verification': 'En attente de vérification...',
      'click_link_first': 'Veuillez d\'abord cliquer sur le lien dans votre e-mail',
      'click_link_then_tap': 'Ouvrez Gmail, cliquez sur le lien de vérification, puis revenez et appuyez sur \'J\'ai vérifié\' ci-dessous.',
      
      // Admin
      'admin_overview': 'APPARENCE',
      'users': 'Utilisateurs',
      'properties': 'Propriétés',
      'cities': 'Villes',
      'verifications': 'Vérifications',
      'reports': 'Rapports',
      'support': 'Support',
      'account_settings': 'PARAMÈTRES DU COMPTE',
      'user_role': 'Rôle Utilisateur',
      'change_password': 'Changer le mot de passe',
      'full_name': 'Nom complet',
      'full_name_hint': 'Entrez votre nom complet',
      'confirm_password': 'Confirmer le mot de passe',
      'confirm_password_hint': 'Confirmez votre mot de passe',
      'passwords_dont_match': 'Les mots de passe ne correspondent pas',
      'sign_in_to_continue': 'Connectez-vous pour continuer',
      'sign_in_up_button': 'Connexion / Inscription',
      'continue_browsing': 'Continuer la navigation',
      'press_back_to_close': 'Appuyez à nouveau pour quitter',
      'no_results_found': 'Aucun résultat trouvé',
      'near_you_at': 'Près de vous',
      'near_you_dash': 'Près de vous — {city}',
      'no_listings_near_you': 'Aucune annonce {filter}proche de vous pour le moment',
      'get_verified': 'Vérifiez votre compte',
      'upload_docs_desc': 'Téléchargez les documents pour vérification',
      'verification_pending': 'Vérification en cours',
      'wait_admin_approval': 'Attendez l\'approbation de l\'administrateur',
      'verification_rejected': 'Vérification rejetée',
      'reupload_rejected_docs': 'Vos documents ont été rejetés. Veuillez les télécharger à nouveau.',
      're_verify': 'Ré-vérifier',
      'verify': 'Vérifier',
      'welcome_for_first_time': 'Bienvenue pour la première fois,',
      'upgrade_to_premium': 'Passer au Premium ?',
      'upgrade_premium_desc': 'Saviez-vous que les propriétaires Premium voient leurs propriétés listées tout en haut des résultats de recherche et bénéficient d\'annonces illimitées ?\n\nSouhaitez-vous passer au Premium avant de publier ?',
      'maybe_later': 'Plus tard',
      'yes_upgrade': 'Oui, Premium',
      'let_get_started': 'Commençons',
      'welcome_home237': 'Bienvenue sur Home237 !',
      'landlord_welcome_body': 'La meilleure plateforme pour gérer vos propriétés au Cameroun 🇨🇲. Nous sommes ravis de vous avoir ici !',
      'overview': 'Aperçu',
      'total_properties': 'Total des propriétés',
      'active': 'Actives',
      'pending_tours': 'Visites en attente',
      'total_views': 'Total des vues',
      'quick_actions': 'Actions rapides',
      'add_property': 'Ajouter une propriété',
      'upgrade': 'Mettre à niveau',
      'explore_properties': 'Explorer les propriétés',
      'all_regions': 'Toutes les régions',
      'search_explore_hint': 'Rechercher par ville, quartier ou type…',
      'featured_caps': 'EN VEDETTE',
      'no_properties_found': 'Aucune propriété trouvée',
      'no_results_for': 'Aucun résultat pour "{query}"',
      'try_different_keyword': 'Essayez un autre mot-clé',
      'try_different_area': 'Essayez un autre quartier ou région',
      'logout_confirm': 'Êtes-vous sûr de vouloir vous déconnecter ?',
      'privacy_security': 'Confidentialité et Sécurité',
      'notifications': 'NOTIFICATIONS',
      'push_notifications': 'Notifications Push',
      'email_marketing': 'Marketing par E-mail',
      'legal': 'JURIDIQUE',
      'tos': 'Conditions d\'utilisation',
      'privacy_policy': 'Politique de confidentialité',
      'delete_account': 'Supprimer le compte',
      'delete_account_desc': 'Supprimer définitivement votre compte et vos données',
      'version': 'Version',
      'change_password_title': 'Changer le mot de passe',
      'current_password': 'Mot de passe actuel',
      'new_password': 'Nouveau mot de passe',
      'confirm_new_password': 'Confirmer le nouveau mot de passe',
      'password_updated': 'Mot de passe changé avec succès !',
      'phone_number': 'Numéro de téléphone',
      'phone_number_required': 'Veuillez entrer votre numéro de téléphone',
      'photo_permission_required': 'Veuillez activer l\'autorisation de photo dans les paramètres',
      'photo_permission_denied': 'Autorisation de photo refusée',

      // Bottom Nav
      'nav_home': 'ACCUEIL',
      'nav_explore': 'EXPLORER',
      'nav_saved': 'ENREGISTRÉ',
      'nav_messages': 'MESSAGES',
      'nav_profile': 'PROFIL',
      'nav_dashboard': 'TABLEAU DE BORD',
      'nav_properties': 'PROPRIÉTÉS',
      'nav_tours': 'VISITES',

      // Onboarding
      'skip': 'Passer',
      'welcome_home237_intro': 'La plateforme n°1 pour trouver et lister\ndes maisons au Cameroun 🇨🇲',
      'browse': 'Parcourir',
      'save': 'Enregistrer',
      'chat': 'Discuter',
      'tour': 'Visiter',
      'everything_you_need': 'Tout ce dont vous avez besoin',
      'hunter_effortless_body': 'Découvrez les fonctionnalités qui rendent\nla recherche de logement facile.',
      'verified_listings_title': 'Annonces vérifiées',
      'verified_listings_body': 'Chaque propriété est examinée et approuvée par notre équipe.',
      'find_near_you_title': 'Trouver près de chez vous',
      'find_near_you_body': 'Parcourez les propriétés les plus proches de votre position actuelle au Cameroun.',
      'chat_landlords_title': 'Discuter avec les propriétaires',
      'chat_landlords_body': 'Envoyez des messages aux propriétaires et planifiez des visites.',
      'save_favorites_title': 'Enregistrer les favoris',
      'save_favorites_body': 'Mettez des propriétés en favoris et revenez-y à tout moment.',
      'where_looking': 'Où cherchez-vous ?',
      'personalize_feed_body': 'Nous personnaliserons votre flux\nen fonction de votre position au Cameroun.',
      'detect_my_location': 'Détecter ma position',
      'detecting_your_location': 'Détection de votre position...',
      'city_detected': '📍 {city} détecté !',
      'change_city': 'Changer de ville',
      'location_not_available_pick': 'Position non disponible. Veuillez choisir une ville.',
      'or_choose_city': 'Ou choisissez une ville :',
      'select_city_continue': 'Choisissez une ville pour continuer',
      'explore_in_city': 'Explorer à {city} 🏠',
      'next_location_setup': 'Suivant — Configuration du lieu',
      
      // Validation
      'err_email_empty': 'Veuillez entrer votre email',
      'err_email_invalid': 'Veuillez entrer un email valide',
      'err_password_empty': 'Veuillez entrer votre mot de passe',
      'err_name_empty': 'Veuillez entrer votre nom complet',
      'err_confirm_password_empty': 'Veuillez confirmer votre mot de passe',
      'password_too_short': 'Le mot de passe doit contenir au moins 6 caractères',
      
      // Profile
      'edit_profile': 'Modifier le Profil',
      'personal_info': 'INFORMATIONS PERSONNELLES',
      'business_info': 'INFORMATIONS COMMERCIALES',
      'rental_pref': 'PRÉFÉRENCES DE LOCATION',
      'pref_location': 'Emplacement Préféré',
      'prop_type': 'Type de Propriété',
      'min_budget': 'Budget Min (FCFA)',
      'max_budget': 'Budget Max (FCFA)',
      'tap_change_photo': 'Appuyez pour changer la photo',
      'save_changes': 'Enregistrer',
      'business_email': 'Email Professionnel',
      'company_name': 'Nom de l\'Entreprise',
      'address': 'Adresse de la Propriété',
      'verified_landlord': 'PROPRIÉTAIRE VÉRIFIÉ',
      'delete_permanently': 'Supprimer Définitivement',
      'enter_password_confirm': 'Entrez votre mot de passe pour confirmer :',
      'delete_warning_tenant': 'Cette action est permanente et supprimera toutes vos données, y compris les propriétés enregistrées, les messages et votre profil.',
      'delete_warning_landlord': 'Cette action est permanente et supprimera toutes vos données, y compris les propriétés et les favoris.',
      'studio': 'Studio',
      '1bed': '1 Chambre',
      '2bed': '2 Chambres',
      '3bed': '3+ Chambres',
      'house': 'Maison',
      'condo': 'Condo',
      'profile_updated': 'Profil mis à jour avec succès !',
      'photo_updated': 'Photo de profil mise à jour !',
      
      // Roles
      'tenant': 'Locataire',
      'landlord': 'Propriétaire',
      'tenant_desc': 'Cherche un logement à louer',
      'landlord_desc': 'A des propriétés à louer',
      'select_role': 'Choisissez votre rôle',
      
      // Terms and Privacy
      'tos_title': 'Conditions d\'utilisation',
      'tos_updated': 'Dernière mise à jour : 4 Mars 2026',
      'tos_s1_t': '1. Acceptation des conditions',
      'tos_s1_b': 'En accédant et en utilisant l\'application Home237, vous acceptez d\'être lié par les termes et dispositions de cet accord. Si vous n\'acceptez pas de respecter ce qui précède, veuillez ne pas utiliser ce service.',
      'tos_s2_t': '2. Responsabilités de l\'utilisateur',
      'tos_s2_b': 'Vous devez avoir au moins 18 ans pour utiliser cette application. En utilisant l\'application, vous garantissez que vous avez au moins 18 ans. Vous acceptez d\'utiliser l\'application uniquement à des fins licites et d\'une manière qui ne porte pas atteinte aux droits d\'autrui.',
      'tos_s3_t': '3. Annonces de propriétés',
      'tos_s3_b': 'Les propriétaires sont responsables de l\'exactitude de leurs annonces de propriétés. Home237 ne vérifie pas toutes les affirmations des annonces et n\'est pas responsable des divergences entre les caractéristiques répertoriées et les caractéristiques réelles de la propriété.',
      'tos_s4_t': '4. Paiements et abonnements',
      'tos_s4_b': 'Certaines fonctionnalités de l\'application nécessitent un paiement. Tous les frais sont indiqués en FCFA et ne sont pas remboursables, sauf disposition expresse de la loi applicable. Les abonnements premium se renouvellent automatiquement jusqu\'à leur annulation.',
      'tos_s5_t': '5. Propriété intellectuelle',
      'tos_s5_b': 'L\'application et son contenu original, ses caractéristiques et ses fonctionnalités sont la propriété de Home237 et sont protégés par les lois applicables sur la propriété intellectuelle.',
      'tos_s6_t': '6. Limitation de responsabilité',
      'tos_s6_b': 'Home237 ne sera pas responsable des dommages indirects, accessoires, spéciaux, consécutifs ou punitifs, y compris la perte de profits ou de données, résultant de votre utilisation du service.',
      'tos_s7_t': '7. Résiliation',
      'tos_s7_b': 'Nous pouvons résilier ou suspendre votre compte et votre accès au service immédiatement, sans préavis, si vous ne respectez pas ces conditions.',
      'tos_s8_t': '8. Modifications des conditions',
      'tos_s8_b': 'Nous nous réservons le droit de modifier ou de remplacer ces conditions à tout moment. En continuant à utiliser le service après l\'entrée en vigueur de modifications, vous acceptez d\'être lié par les conditions révisées.',
      'tos_s9_t': '9. Droit applicable',
      'tos_s9_b': 'Ces conditions sont régies et interprétées conformément aux lois du Cameroun, sans égard à ses dispositions en matière de conflit de lois.',
      'tos_s10_t': '10. Contactez-nous',
      'tos_s10_b': 'Si vous avez des questions concernant ces conditions, veuillez nous contacter à l\'adresse suivante :\nlegal@home237.com',
      'pp_title': 'Politique de confidentialité',
      'pp_updated': 'Dernière mise à jour : 4 Mars 2026',
      'pp_s1_t': '1. Informations que nous collectons',
      'pp_s1_b': 'Nous collectons les informations que vous nous fournissez directement, par exemple lorsque vous créez un compte, notamment votre nom, votre adresse e-mail, votre numéro de téléphone, votre photo de profil et vos préférences en matière de propriété. Nous collectons également des informations automatiquement lorsque vous utilisez l\'application, telles que votre adresse IP et les informations sur votre appareil.',
      'pp_s2_t': '2. Comment nous utilisons vos informations',
      'pp_s2_b': 'Nous utilisons les informations que nous collectons pour :\n• Fournir, exploiter et maintenir nos services\n• Traiter les transactions et envoyer les informations associées\n• Envoyer des communications promotionnelles (si autorisé)\n• Répondre à vos commentaires et questions\n• Surveiller et analyser l\'utilisation et les tendances',
      'pp_s3_t': '3. Partage des informations',
      'pp_s3_b': 'Nous pouvons partager vos informations avec :\n• Les propriétaires ou les locataires pour faciliter les transactions immobilières\n• Les prestataires de services tiers qui effectuent des services en notre nom\n• Les forces de l\'ordre lorsque la loi l\'exige\n\nNous ne vendons pas vos informations personnelles à des tiers.',
      'pp_s4_t': '4. Sécurité des données',
      'pp_s4_b': 'Nous prenons des mesures raisonnables, notamment des garanties administratives, techniques et physiques, pour protéger vos informations contre la perte, le vol, l\'utilisation abusive et l\'accès non autorisé. Cependant, aucune transmission sur Internet n\'est complètement sécurisée.',
      'pp_s5_t': '5. Conservation des données',
      'pp_s5_b': 'Nous conservons vos informations personnelles tant que votre compte est actif ou selon les besoins pour vous fournir des services et nous conformer à nos obligations légales.',
      'pp_s6_t': '6. Cookies et suivi',
      'pp_s6_b': 'Nous pouvons utiliser des cookies et des technologies de suivi similaires pour suivre l\'activité sur notre application et conserver certaines informations afin d\'améliorer votre expérience utilisateur.',
      'pp_s7_t': '7. Vos droits et choix',
      'pp_s7_b': 'Vous pouvez :\n• Accéder aux informations de votre compte et les mettre à jour à tout moment\n• Désactiver les e-mails promotionnels\n• Demander la suppression de votre compte en envoyant un e-mail à support@home237.com\n• Demander une copie de vos données personnelles',
      'pp_s8_t': '8. Confidentialité des enfants',
      'pp_s8_b': 'Notre service ne s\'adresse pas aux enfants de moins de 18 ans. Nous ne collectons pas sciemment d\'informations personnelles auprès d\'enfants de moins de 18 ans.',
      'pp_s9_t': '9. Modifications de cette politique',
      'pp_s9_b': 'Nous pouvons mettre à jour cette politique de confidentialité de temps à autre. Nous vous informerons de tout changement en publiant la nouvelle politique sur cette page avec une date mise à jour.',
      'pp_s10_t': '10. Contactez-nous',
      'pp_s10_b': 'Si vous avez des questions concernant cette politique de confidentialité, veuillez nous contacter à :\nprivacy@home237.com\n\nHome237 — Connecter les locataires et les propriétaires du Cameroun.',
      'tos_footer': '© 2026 Home237. Tous droits réservés.',
      'pp_footer': '© 2026 Home237. Tous droits réservés.',
    },
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'fr'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_) => false;
}
