// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqD7Yc9UlEMIKf41R_GFgILu_ldS8tvco',
    appId: '1:254664754146:android:34d04e9d9bb0ced3196fbb',
    messagingSenderId: '254664754146',
    projectId: 'home237-92c18',
    storageBucket: 'home237-92c18.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9GbwtiSjyZhO9S1p6Fb2AjpF4Lhb5bPs',
    appId: '1:254664754146:web:1eca99980d063175196fbb',
    messagingSenderId: '254664754146',
    projectId: 'home237-92c18',
    authDomain: 'home237-92c18.firebaseapp.com',
    storageBucket: 'home237-92c18.firebasestorage.app',
    measurementId: 'G-VGTE9D5GPE',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADor6z6lNOiy4RekN4li2KIA-gvNmoS7c',
    appId: '1:254664754146:ios:396930de2a1beee4196fbb',
    messagingSenderId: '254664754146',
    projectId: 'home237-92c18',
    storageBucket: 'home237-92c18.firebasestorage.app',
    iosClientId: '254664754146-g1apl9nar94obhifkj563kk4hf79907r.apps.googleusercontent.com',
    iosBundleId: 'com.example.home237',
  );

}